### ISSUE TITLE
Levelset example not giving same solution

### ISSUE THREAD

**Issue by prjaga** [prjaga/fireshape#3]
The levelset example should give an optimised shape of a circle of radius $1/\sqrt{2}$ centered at $(0.5, 0.5)$. The built in levelset example in Fireshape does this and when I ran the same example on the script found in [level set sketch](https://github.com/colinjcotter/shape_optimization_sketches/blob/main/level_set.py). I also get the same result. For some reason now that my control space is working inside of fireshape the shape is moving but it is blowing up to have a radius closer to 3 which is wrong.

**Comment by prjaga** [comment]
Tried increasing nstep in run_forward, doesnt seem to do anything

**Comment by prjaga** [comment]
Tried to assign p0 in restrict before computing the derivative, doesnt seem to do anything

**Comment by prjaga** [comment]
Tried to reduce the scale parameter in the objective, doesnt seem to do anything

**Comment by prjaga** [comment]
Added a new mesh (`mesh_c`). So now we have 
- `mesh_c` (Control mesh, the mesh where p0 is defined, so this is the square inside the square for the levelset examples)
- `mesh_r` (Reference mesh where the V_r is defined on, just the inner square)
- `mesh_m` (Moved mesh where V_m is defined on, just the inner square)

I moved all the functions defined in the constructor for the forward model to V_c which is a vector function space on `mesh_c`. I then defined an fd.Interpolator just like in FeControlSpace (when `mesh_c` is defined in there). 

In interpolate we run the forward model as usual to obtain dphi in V_c which we then interpolate onto V_r using the interpolator.  

In restrict since the residual parameter is in V_r_dual I first interpolate this cofunction back into V_c_dual using the interpolator and save this value into `self.residual` then we run the same backwards model as before with the taping and calling derivative to get dJ/dp instead of dJ/dphi.

Still running into the same issue where the shape blows up and also the taylor test does not converge again with the same issues

```
           Step size           grad'*dir           FD approx           abs error
           ---------           ---------           ---------           ---------
   1.00000000000e+00   3.01363871854e-03   6.16652163101e-03   3.15288291247e-03
   1.00000000000e-01   3.01363871854e-03   9.66684270958e-02   9.36547883773e-02
   1.00000000000e-02   3.01363871854e-03   1.29651906661e+00   1.29350542789e+00
   1.00000000000e-03   3.01363871854e-03   1.63202185810e+01   1.63172049423e+01
   1.00000000000e-04   3.01363871854e-03   1.97586608093e+02   1.97583594455e+02
```

I think the issue might be in restrict and that I'm not applying the chain rule correctly somewhere

https://github.com/prjaga/fireshape/blob/pj/newcontrolspace/fireshape/control.py#L198C3-L238

**Comment by prjaga** [comment]
Trying to code own version of the taylor test. The code is at
https://github.com/prjaga/fireshape/blob/pj/newcontrolspace/examples/levelset_cm/levelset_cm.py#L68-L115

In general still the same issue of error increasing as t decreases. I noticed some other things which I am not sure how to explain. The results for all these are in a comment below the code in the link above.
- When running the numerical tests for 0.1 till 0.001 and then for 1 till 0.001 I do not get the same values for the error. I think this is because our update is moving the mesh over timesteps
- The numbers I get in my numerical tests are not the same as what ROL returns but they are the same orders of magnitude in general (this could be related to the previous problem)

**Comment by colinjcotter** [comment]
OK I have a guess as to what is going wrong. The error is blowing up because the FD approx is itself blowing up. This would happen if the numerator is staying constant but the denominator is getting smaller (the latter is of course happening). So I wonder if the forward functional is not changing correctly? The FD approx should be converging to something but it is diverging currently - this suggests a problem with the forward functional (maybe phi is not updated or something?).

**Comment by prjaga** [comment]
I ran a little test like this where ideally the first and third number should be the same and the second and fourth. But that is not what I get

```python
x = q.clone()
x.fun.assign(1)

y = q.clone()
y.fun.assign(2)

J.update(x, None, -1)
print(J.value(None, None))

J.update(y, None, -1)
print(J.value(None, None))

J.update(x, None, -1)
print(J.value(None, None))

J.update(y, None, -1)
print(J.value(None, None))
```
The output I get is 
```
-0.3738330484376182
0.0576701941276003
0.46828997824172514
1.5799644293760444
```
For some reason the forward model in each iteration is not resulting in the same shape for given control vectors. So I think phi is being updated just updated wrong

**Comment by prjaga** [comment]
Tried it with

```python
x = q.clone()
x.fun.assign(1)

y = q.clone()
y.fun.assign(2)

J.update(x, None, -1)
print(J.value(None, None))

J.update(y, None, -1)
print(J.value(None, None))

x.fun.assign(1)
J.update(x, None, -1)
print(J.value(None, None))

y.fun.assign(2)
J.update(y, None, -1)
print(J.value(None, None))
```

in case the control vectors were getting in between runs but does not seem to be the case as the results are

```
-0.37410849402208113
0.050958565380200785
0.45803487153245387
1.5602561807351194
```

**Comment by prjaga** [comment]
In run forward tried to reset dphi to 0 before stepping through like 

```python
    def run_forward(self):
        self.dphi.assign(0)
        for _ in range(self.nstep):
            fd.solve(self.a == self.L, self.u0, bcs=self.bcs)
            self.dphi.interpolate(self.dphi + self.dt * self.u0)
```

and this gives new ROL results of

```
           Step size           grad'*dir           FD approx           abs error
           ---------           ---------           ---------           ---------
   1.00000000000e+00   4.42496052308e-04   4.48165454827e-04   5.66940251967e-06
   1.00000000000e-01   4.42496052308e-04   4.43063223751e-04   5.67171442980e-07
   1.00000000000e-02   4.42496052308e-04   4.42552771812e-04   5.67195044841e-08
   1.00000000000e-03   4.42496052308e-04   4.42501724318e-04   5.67201047442e-09
```

which is more promising

**Comment by colinjcotter** [comment]
Looks great! Yes, you are right, we do have to reset dphi to zero.

This is showing 1st order convergence so things are working now.
